# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(400, 250)
        main_window.setMinimumSize(QtCore.QSize(400, 250))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        main_window.setPalette(palette)
        main_window.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.directory_field = QtWidgets.QLineEdit(self.frame)
        self.directory_field.setObjectName("directory_field")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.directory_field)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.depth_field = QtWidgets.QLineEdit(self.frame)
        self.depth_field.setObjectName("depth_field")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.depth_field)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.repeat_radio = QtWidgets.QRadioButton(self.frame_2)
        self.repeat_radio.setChecked(True)
        self.repeat_radio.setObjectName("repeat_radio")
        self.horizontalLayout.addWidget(self.repeat_radio)
        self.no_repeat_radio = QtWidgets.QRadioButton(self.frame_2)
        self.no_repeat_radio.setObjectName("no_repeat_radio")
        self.horizontalLayout.addWidget(self.no_repeat_radio)
        self.reset_button = QtWidgets.QPushButton(self.frame_2)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout.addWidget(self.reset_button)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.random_button = QtWidgets.QPushButton(self.frame_3)
        self.random_button.setObjectName("random_button")
        self.horizontalLayout_2.addWidget(self.random_button)
        self.open_button = QtWidgets.QPushButton(self.frame_3)
        self.open_button.setObjectName("open_button")
        self.horizontalLayout_2.addWidget(self.open_button)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.output_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.output_box.setObjectName("output_box")
        self.verticalLayout_3.addWidget(self.output_box)
        main_window.setCentralWidget(self.centralwidget)
        self.create_delete_button = QtWidgets.QAction(main_window)
        self.create_delete_button.setObjectName("create_delete_button")
        self.actionf = QtWidgets.QAction(main_window)
        self.actionf.setObjectName("actionf")
        self.actiong = QtWidgets.QAction(main_window)
        self.actiong.setObjectName("actiong")
        self.set_directory_button = QtWidgets.QAction(main_window)
        self.set_directory_button.setObjectName("set_directory_button")
        self.refresh_button = QtWidgets.QAction(main_window)
        self.refresh_button.setObjectName("refresh_button")
        self.scan_button = QtWidgets.QAction(main_window)
        self.scan_button.setObjectName("scan_button")
        self.backup_button = QtWidgets.QAction(main_window)
        self.backup_button.setObjectName("backup_button")
        self.load_button = QtWidgets.QAction(main_window)
        self.load_button.setObjectName("load_button")
        self.edit_action = QtWidgets.QAction(main_window)
        self.edit_action.setObjectName("edit_action")
        self.delete_action = QtWidgets.QAction(main_window)
        self.delete_action.setObjectName("delete_action")
        self.clear_filter_action = QtWidgets.QAction(main_window)
        self.clear_filter_action.setObjectName("clear_filter_action")

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "File Picker"))
        self.label.setText(_translate("main_window", "Directory"))
        self.label_2.setText(_translate("main_window", "Depth"))
        self.depth_field.setText(_translate("main_window", "1"))
        self.repeat_radio.setText(_translate("main_window", "Allow Repeats"))
        self.no_repeat_radio.setText(_translate("main_window", "Do Not Allow Repeats"))
        self.reset_button.setText(_translate("main_window", "Reset Repeats"))
        self.random_button.setText(_translate("main_window", "Random"))
        self.open_button.setText(_translate("main_window", "Open"))
        self.create_delete_button.setText(_translate("main_window", "Create and Delete"))
        self.actionf.setText(_translate("main_window", "f"))
        self.actiong.setText(_translate("main_window", "g"))
        self.set_directory_button.setText(_translate("main_window", "Set Directory"))
        self.refresh_button.setText(_translate("main_window", "Refresh"))
        self.scan_button.setText(_translate("main_window", "Scan Directory"))
        self.backup_button.setText(_translate("main_window", "Backup Database"))
        self.load_button.setText(_translate("main_window", "Load Backup"))
        self.edit_action.setText(_translate("main_window", "Edit"))
        self.delete_action.setText(_translate("main_window", "Delete"))
        self.clear_filter_action.setText(_translate("main_window", "Clear Filter"))
